# Generated by Django 4.0.5 on 2022-09-15 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saraiyascope', '0004_currentframe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeeksModel',
        ),
        migrations.DeleteModel(
            name='TerrysModel',
        ),
    ]
